# Generated by Django 5.2.3 on 2025-06-19 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_service', '0002_roomreservation_date_end_roomreservation_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
